import "./globals.css";
import "@szhsin/react-menu/dist/index.css";
import "@szhsin/react-menu/dist/transitions/slide.css";
import { Satoshi } from "../../utils/customFonts";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import AllProvider from "./components/ToastContainer";
import { NavigationProvider } from "./contexts";

export const metadata = {
  title: "NG Pay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${GeistSans.variable} ${Satoshi.variable} font-geistSans text-neutral-900`}
        suppressHydrationWarning={true}
      >
        <AllProvider>
          <NavigationProvider>{children}</NavigationProvider>
        </AllProvider>
      </body>
    </html>
  );
}
