import { Inter } from "next/font/google";
import "./globals.css";
import { Satoshi } from "../../utils/customFonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NG Pay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${Satoshi.variable} font-satoshi text-neutral-900`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
