import "./globals.css";
import "@szhsin/react-menu/dist/index.css";
import "@szhsin/react-menu/dist/transitions/slide.css";
import { Satoshi } from "../../utils/customFonts";

export const metadata = {
  title: "NG Pay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${Satoshi.variable} font-satoshi text-neutral-900`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
