export const teamsTable = [
  {
    role: "admin",
    last_active: "20240801",
    email: "ozfeasi@nanulo.kn",
    date_added: "20240801",
    name: "Richard Murray",
    status: "active",
  },
  {
    role: "admin",
    last_active: "20240801",
    email: "catlafkoc@zife.cy",
    date_added: "20240801",
    name: "Howard Miller",
    status: "active",
  },
  {
    role: "operator",
    last_active: "20240801",
    email: "foavudu@gupufbu.kp",
    date_added: "20240801",
    name: "Sean Stevens",
    status: "active",
  },
  {
    role: "admin",
    last_active: "20240801",
    email: "eftig@ba.cf",
    date_added: "20240801",
    name: "Eunice Elliott",
    status: "disabled",
  },
  {
    role: "agent",
    last_active: "20240801",
    email: "hi@adaahake.na",
    date_added: "20240801",
    name: "Lenora Becker",
    status: "inactive",
  },
  {
    role: "admin",
    last_active: "20240801",
    email: "vutva@tinulu.aq",
    date_added: "20240801",
    name: "Alberta Watts",
    status: "active",
  },
  {
    role: "operator",
    last_active: "20240801",
    email: "rad@zi.sa",
    date_added: "20240801",
    name: "Chase Knight",
    status: "active",
  },
  {
    role: "agent",
    last_active: "20240801",
    email: "duboisa@atohedog.ai",
    date_added: "20240801",
    name: "Janie Green",
    status: "active",
  },
  {
    role: "agent",
    last_active: "20240801",
    email: "epweddu@me.tv",
    date_added: "20240801",
    name: "Agnes Wood",
    status: "active",
  },
];

export const teamsTableColumns = [
  {
    key: "name",
    dataIndex: "name",
    title: "Name",
    width: 300,
    hidden: false,
  },
  {
    key: "role",
    dataIndex: "role",
    title: "Role",
    width: 100,
    hidden: false,
  },
  {
    key: "date_added",
    dataIndex: "date_added",
    title: "Date Added",
    width: 120,
    hidden: false,
  },
  {
    key: "last_active",
    dataIndex: "last_active",
    title: "Last Active",
    width: 120,
    hidden: false,
  },
  {
    key: "actions",
    dataIndex: "actions",
    title: "Actions",
    width: 200,
    hidden: false,
  },
];
